name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install .
          pip install build
          pip install twine

      - name: Run tests
        run: python -m unittest discover test

  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2

      - name: Run GitVersion
        id: gitversion
        run: gitversion /output json /showvariable FullSemVer

      - name: Display Version
        run: "echo 'Generated version: ${{ steps.gitversion.outputs.FullSemVer }}'"

      - name: Create Git Tag
        if: github.ref == 'refs/heads/master'
        run: |
          VERSION=${{ steps.gitversion.outputs.FullSemVer }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
