name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install .
          pip install build
          pip install twine

      - name: Run tests
        run: python -m unittest discover test

  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true

      - name: Display Version
        run: "echo Generated version: ${{ steps.version_step.outputs.FullSemVer }}"

      - name: Create Git Tag
        # if: github.ref == 'refs/heads/main'
        run: |
          VERSION=${{ steps.gitversion.outputs.FullSemVer }}
          echo "Tagging version: $VERSION"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
      
